### ISSUE TITLE
Missing Numeric Option

### ISSUE THREAD

**Issue by epicacrylic** [Bandit-bytes/betterHP#3]
You do not have an option to enable/disable the numeric health icon, only the oxygen and hunger ones

**Comment by Bandit-bytes** [comment]
Fabric or forge

**Comment by epicacrylic** [comment]
NeoForge 47.1.106
Better HP 5.3.0

Sorry, idk why I completely forgot to post that in the first post

**Comment by Bandit-bytes** [comment]
> NeoForge 47.1.106 Better HP 5.3.0
> 
> Sorry, idk why I completely forgot to post that in the first post

this works on neoforge 1.20.1 ?

**Comment by Bandit-bytes** [comment]
i've added the configurable option and uploaded to CF v5.6.0

**Comment by Bandit-bytes** [comment]
You may need to gen a new config :)

**Comment by epicacrylic** [comment]
Works now, thank you ^^
