### ISSUE TITLE
Feature request - Fabric mod menu compatibility! 

### ISSUE THREAD

**Issue by AkkiTheGamerFox** [Bandit-bytes/betterHP#4]
Please add this, manually editing the config is very annoying, and for some reason likes to reset.

**Comment by Bandit-bytes** [comment]
Cloth ? Or what mod modMenu I think it's called yeah?

**Comment by AkkiTheGamerFox** [comment]
> Cloth ? Or what mod modMenu I think it's called yeah?

Yeah, it's this one. https://www.curseforge.com/minecraft/mc-mods/modmenu

**Comment by Bandit-bytes** [comment]
Will look into tonight or tomorrow

**Comment by Bandit-bytes** [comment]
Added ModMenu for this, new version will be live when ever CF/Modrinth approve

**Comment by Bandit-bytes** [comment]
You will need to gen a new config file for new modmenu api
