### ISSUE TITLE
Thanks to the author of the mod, this is the Chinese language configuration file I do

### ISSUE THREAD

**Issue by LimitXiaoHuoChai** [Bandit-bytes/betterHP#5]
Thanks to the author of the mod, this is the Chinese language configuration file I do
[zh_cn.json](https://github.com/user-attachments/files/17500985/zh_cn.json)

**Comment by Bandit-bytes** [comment]
I will add this, this weekend thank you for the patience and providing the lang

**Comment by Bandit-bytes** [comment]
sorry it took so long, i had to write in the ability to use language it was all literal. updated mod to support lang and re wrote the chinese lang file as well. in latest 1.20.1 forge version now

**Comment by LimitXiaoHuoChai** [comment]
All right, all right.
