### ISSUE TITLE
[Request] Additional Compatibility

### ISSUE THREAD

**Issue by DancinWhale** [Bandit-bytes/betterHP#8]
This is a great mod and I would love to add it to my modpack if it was compatible with Ars Nouveau (magic mod), Iron's Spells 'n Spellbooks (another magic mod) and Feathers (By ElenaiDev).

**Comment by Bandit-bytes** [comment]
hello! it odes work with these mods, i have them in a modpack the thing i did was adjust the location of the irons mana pool to the bottom left as well as Ars Nouveau mana pool to the bottom left above irons. and for feathers you can adjust that slight above the oxygen section and you can set feathers to only display if used so its not always on ( better for FPS) !
